[package]
name = "Utf8"
version = "0.1.0"
authors = ["Richard Walters <rwalters@digitalstirling.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
bstr = "0.2"
